### ISSUE TITLE
autofix might not work for 100%?

### ISSUE THREAD

**Issue by bastelfreak** [kuleuven/puppet-lint-manifest_whitespace-check#1]
Hi,
thanks for the plugin! I was looking for something like this for a long time. Awesome that you created it! I tested it on the voxpupuli/puppet-zabbix modul, the autofix created the following diff:

```diff
-) inherits zabbix::params {
+)inherits zabbix::params {
```

I'm not 100% sure this is correct, but I guess there should be a whitespace between `)` and `inherits`?

**Comment by jovandeginste** [comment]
I agree there should. It's not 100% yet, and there is a lot of stuff I want to add... I'm happy I'm not the only one with this itch :-)

**Comment by jovandeginste** [comment]
@bastelfreak Should be fixed now (I added specific tests for this)
