### ISSUE TITLE
Fails with heredoc and interpolated variables

### ISSUE THREAD

**Issue by bastelfreak** [kuleuven/puppet-lint-manifest_whitespace-check#10]
Hi,
I've the following code:
```puppet
file { '/tmp/test':
  ensure  => file,
  owner   => 'root',
  group   => 'root',
  content => Sensitive(@("EOF")),
  # hostname:port:database:username:password
  127.0.0.1:5432:aos:${variable}:${hash['password']}
  localhost:5432:aos:${variable}:${hash['password']}
  | EOF
}
```

this fails with a manifest_whitespace_closing_brace_before error message. I tested this on puppet-lint 2.5.0 and puppet-lint-manifest_whitespace-check 0.1.17

**Comment by greatflyingsteve** [comment]
As a workaround, moving the heredoc outside of the resource body also seems to make this check happy, but this solution is not always cleaner.
