### ISSUE TITLE
Error on space before opening bracket, no code change

### ISSUE THREAD

**Issue by wkorevaar** [kuleuven/puppet-lint-manifest_whitespace-check#17]
Since monday we are running into some issues on spaces before opening bracket.

for example:

```puppet
if ("${var}" in fact.keys) and (fact["${var}"] != $var2.keys[0]) {
```

it gives an error on the fact that there is no space between keys and the brackets.
So in the linting it goes wrong on the line stated above, but it succeeds on 

```puppet
if ("${var}" in fact.keys) and (fact["${var}"] != $var2.keys [0]) {
```

The problem is that adding a space here breaks the code.

Other places we have this error:

```puppet
  Array   $var=lookup('foo::bar',Array,undef,[])
```
This succeeds as 

```puppet
  Array   $var=lookup('foo::bar',Array,undef, [])
```

adding a space here doens't break the code, but it isn't as neat as without the space.

**Comment by jovandeginste** [comment]
The `fact[...]` syntax was a bug in the linter; I do believe, however, there should be spaces inside the function

```puppet
  Array   $var=lookup('foo::bar',Array,undef,[])
```

should be (IMO):

```puppet
  Array   $var = lookup('foo::bar', Array, undef, [])
```
