### ISSUE TITLE
Heredoc string interpolation provides false positives

### ISSUE THREAD

**Issue by jbh** [kuleuven/puppet-lint-manifest_whitespace-check#19]
When using Heredoc with string interpolation, the puppet-lint gives false positives:

```puppet
class test::heredoc {
  $unsupported = @("MESSAGE"/L)
    This does not support ${facts['os']['name']} ${$facts['os']['release']['major']}; \
    see ${support_urls['supported_platforms']} for more information\
    | MESSAGE

  fail($unsupported)
}
```

puppet-lint returns:
```
pdk (ERROR): puppet-lint: there should be either a bracket, punctuation mark, closing quote or a newline after a closing bracket, or whitespace and none of the aforementioned (manifests/heredoc.pp:3:48)
```

I surrounded with `# lint:ignore:manifest_whitespace_closing_bracket_after` just to be sure, and that gets rid of the lint errors.

**Comment by jovandeginste** [comment]
Are you sure you are using the latest version?

**Comment by jovandeginste** [comment]
(I added a test case, which does not fail for me)

**Comment by jbh** [comment]
Good question. I'll be at my computer to officially check the actual version I'm working with here in an hour or two.

In the meantime, looking at my phone to check my repo files, `pdk new module` generates a new module with linters from voxpupuli: `voxpupuli-puppet-lint-plugins`.

I generated my module last week, and it requires voxpupuli-puppet-lint-plugins v3.0 or greater, which doesn't have a version requirement for the manifest whitespace linter.

The module in question: [zend/zend_common](https://github.com/zendtech/puppet-zend-common)

**Comment by jbh** [comment]
Very strange. I can't reproduce the error anymore. I removed the lint ignore, ran `pdk validate`, and all lints passed without issue. I'm going to chalk it up to weird version issues, because I did have to revert my Ruby from `3.1.2` to `2.7.6` a few days ago. Not sure what difference running `2.7.6` now makes, but everything checks out fine now. Sorry for the apparent false alarm!

**Comment by jovandeginste** [comment]
No worry; however, I believe I run 3.1.2 too (on my phone now so can't check)
