### ISSUE TITLE
instead of puring double whitespace, a third one is added

### ISSUE THREAD

**Issue by bastelfreak** [kuleuven/puppet-lint-manifest_whitespace-check#2]
Hi,
given the following code: https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/javagateway.pp#L63

the plugin creates this diff:

```diff
-) inherits zabbix::params  {
+) inherits zabbix::params   {
```

where I expected this:

```diff
-) inherits zabbix::params  {
+) inherits zabbix::params {
```

**Comment by jovandeginste** [comment]
I can reproduce this. I think two checks are fighting each other here...

**Comment by jovandeginste** [comment]
Maybe v0.1.2 fixes this. I hope I can find a way to test multiple checks together, so I can be more sure...

**Comment by jovandeginste** [comment]
@bastelfreak I think this is now fixed. Can you confirm?

**Comment by bastelfreak** [comment]
I can confirm \o/

**Comment by jovandeginste** [comment]
great!
