### ISSUE TITLE
false positive from manifest_whitespace_opening_brace_before

### ISSUE THREAD

**Issue by vchepkov** [kuleuven/puppet-lint-manifest_whitespace-check#22]
linter insists on adding empty space in a list of parameters, when one of them is an empty hash.

For example

`$foo = lookup('foo::bar',Hash,'first',{})`

```
ERROR: there should be a single space before an opening brace on line 1 (check: manifest_whitespace_opening_brace_before)
```

**Comment by jovandeginste** [comment]
This sounds more like we need an extra check that adds spaces after a comma (`,`)
In my opinion, the correct result should be:

```puppet
$foo = lookup('foo::bar', Hash, 'first', {})
```

(See #17)

**Comment by gvde** [comment]
I get the same error even if there is a single space before the opening brace, e.g. for the first two lines of the following I get the error for each:

```
46  $slave_ifnames = $bonds.reduce( {}) |$l, $i| {
47    $l + split($i['attached_devices'], /,/).reduce( {}) |$sl, $d| { $sl + { $d => $i['identifier'] } }
48  }
```

result in:

```
manifests/network.pp - ERROR: there should be a single space before an opening brace on line 46 (check: manifest_whitespace_opening_brace_before)
manifests/network.pp - ERROR: there should be a single space before an opening brace on line 47 (check: manifest_whitespace_opening_brace_before)
```
But there is actually a single space before each opening brace `{`.

This happens with the latest version:
```
Fetching puppet-lint-manifest_whitespace-check 0.2.9
Installing puppet-lint-manifest_whitespace-check 0.2.9
```

The version packaged with pdk 2.5.0 puppet-lint-manifest_whitespace-check-0.1.17 doesn't complain about these two lines.

**Comment by jovandeginste** [comment]
@gvde it seems the error is correct, but the message is wrong; if I remove the space, the linter (v0.2.9) is happy:

```puppet
        $slave_ifnames = $bonds.reduce({}) |$l, $i| {
          $l + split($i['attached_devices'], /,/).reduce({}) |$sl, $d| { $sl + { $d => $i['identifier'] } }
        }
```

I believe this code snippet is correctly formatted...?

I'll look into fixing the error message.

**Comment by gvde** [comment]
@jovandeginste I agree. It looks much better without the space. However, then the validate using pdk 2.5 fails with the same error:

```
pdk (ERROR): puppet-lint: there should be a single space before an opening brace (manifests/network.pp:46:34)
pdk (ERROR): puppet-lint: there should be a single space before an opening brace (manifests/network.pp:47:52)
```

which is why I put those space in there to begin with. pdk 2.5.0 uses puppet-lint-manifest_whitespace-check-0.1.17, so I guess I'll have to ignore that error with pdk until they update to a newer version of puppet-lint-manifest_whitespace-check...

**Comment by jovandeginste** [comment]
That was indeed a bug in the linter at that point, which was reported and fixed since...

**Comment by gvde** [comment]
pdk 2.6.0 is out now. It comes with 0.2.9 and doesn't complain about those spaces anymore...

**Comment by jovandeginste** [comment]
Thank you for the feedback; I will now close the issue.

**Comment by vchepkov** [comment]
I have updated to 0.2.9 and the problem is still there
```
$ gem list|grep white
puppet-lint-manifest_whitespace-check (0.2.9)

$ cat foo.pp 
$foo = lookup('foo::bar',Hash,'first',{})

$ puppet-lint foo.pp 
ERROR: there should be a single space before an opening brace on line 1 (check: manifest_whitespace_opening_brace_before)

```

**Comment by jovandeginste** [comment]
@vchepkov I think you missed my remark: I believe the error is correct, and not a false positive...

**Comment by vchepkov** [comment]
Oh, I might have, but why ? Parameters are separated by `,` without space, what is so special about the last one?

**Comment by jovandeginste** [comment]
Part of my remark was that I believe they all should have a space after each `,` (so that might be an improvement to my linter).

What's special about the last one, is that it is the only one which has braces (`{`). That is the main token I was linting until now. Quotes (`'`) might be another good one to start linting...
