### ISSUE TITLE
whitespace is enforced asymetric

### ISSUE THREAD

**Issue by bastelfreak** [kuleuven/puppet-lint-manifest_whitespace-check#8]
Hi!
first off, sorry for the bad issue title. given the following code:

```puppet
function yum::bool2num_hash_recursive($arg) {
  assert_type(Hash, $arg)
  $arg.map |$key, $value| {
    $return_value = $value ? {
      Boolean => bool2num($value),
      Hash    => yum::bool2num_hash_recursive($value),
      default => $value,
    }
    Hash( { $key => $return_value })
  }.reduce |$attrs_memo, $kv| {
    merge($attrs_memo, $kv)
  }
}
```

this puppet-lint plugin assumes that this code is fine. However I think the following line is bad:

```puppet
    Hash( { $key => $return_value })
```

I don't understand why the plugin enforces a whitespace between `(` and `{`, but not between `}` and `)`. This looks really odd. I think the first space needs to go away or a space should be added at the end.

**Comment by alexjfisher** [comment]
I encountered a similar issue when using `reduce` with an empty hash as the starting value.  eg
```puppet
$servers.reduce({}) |$memo, $server| {
...
}
```

This fails `manifest_whitespace_opening_brace_before`.  Trying to fix it by adding spaces either side of the hash didn't work.
ie
```puppet
$servers.reduce( {} ) |$memo, $server| {
```

Now I get `manifest_whitespace_closing_brace_after`

The plugin *is* happy with
```puppet
$servers.reduce( {}) |$memo, $server| {
```
though.

**Comment by cocker-cc** [comment]
Me too:

```
  $pub_key = ssh_keygen({ name => $username, public => true })                      
leads to: there should be a single space before an opening brace

  $pub_key = ssh_keygen( { name => $username, public => true } )                    
leads to: there should be either a bracket, punctuation mark, closing quote or a newline after a closing brace, or whitespace and none of the aforementioned

only
  $pub_key = ssh_keygen( { name => $username, public => true })                     
is happy
```

**Comment by jovandeginste** [comment]
seems to be fixed

**Comment by natemccurdy** [comment]
@jovandeginste With version `0.2.0` of the gem, I still see inconsistent behavior in this check.

For example, given this manifest, only the first line should pass.
The last three lines should all report a problem:
```
Hash({ $key => $return_value })

Hash( { $key => $return_value } )
Hash( { $key => $return_value })
Hash(       { $key => $return_value })
```

However only line 3 reports a problem:
```
ERROR:manifest_whitespace_closing_brace_after - there should be either a bracket, punctuation mark, closing quote or a newline after a closing brace, or whitespace and none of the aforementioned on line 3
```

Seems like the whitespace to the right of an open parenthesis isn't being checked?

**Comment by jovandeginste** [comment]
Yes, I added tests to track this. Work to be done!

**Comment by jovandeginste** [comment]
I thinks this is fixed in v0.2.1

**Comment by jovandeginste** [comment]
(Please provide more test cases if you find more issues!)

**Comment by natemccurdy** [comment]
Looks fixed to me. thanks!
