### ISSUE TITLE
no whitespace for "${myvar}"

### ISSUE THREAD

**Issue by operatorofhell** [kuleuven/puppet-lint-manifest_whitespace-check#9]
I'm getting following error
`ERROR: there should be a single space before an opening brace on line`
on code like this

` $ my_define { "foo-${myvar}": }`

**Comment by jovandeginste** [comment]
I can't seem to reproduce this ... Is this still an issue?

**Comment by operatorofhell** [comment]
I tried this again with puppet-lint 2.5.2  and the error is gone.
